data: {}
data_availability: To inquire after the data used by these scripts, please contact me directly.
dir_description: The scripts found in this directory are for reproducing the results in Appendix D of my PhD thesis.
prerequisites:
  astropy: 5.0.4
  craft-optical-followup:
    url: https://github.com/Lachimax/craft-optical-followup
    branch: marnoch+2023
  matplotlib: 3.5.2
  numpy: 1.22.3
publication:
  first_author_surname: Marnoch
  multi_author: true
  pubtype: paper
  urls:
    arXiv: null
    DOI: null
  year: 2023
references: [
  'James, C. W. et al 2021:
    *The z–DM distribution of fast radio bursts*,
    MNRAS 509:4:4775-4802
    [https://doi.org/10.1093/mnras/stab3051]',
]