#!/usr/bin/env python
# Code by Lachlan Marnoch, 2023

import os

import craftutils.utils as u
from craftutils.observation.objects import set_cosmology

from lib import *

description = """
Generates the synthetic magnitudes for our FRB hosts at a range of redshifts.
Uses Prospector SED models generated by Gordon et al 2023.
"""


def main(
        output_dir: str,
        input_dir: str,
        cosmo: str,
        write: bool
):
    set_output_path(output_dir)
    model_path = os.path.join(output_path, "sed_models")
    print("write is", write)
    u.mkdir_check(model_path)
    set_input_path(input_dir)
    set_cosmology(cosmo)
    load_prospector_files()
    for i, frb_name in enumerate(model_dict):
        print(f"Processing {i + 1} / {len(model_dict)}:", frb_name, "...")
        model_dict_frb = model_dict[frb_name]
        model = model_dict_frb["model"]
        if write:
            model.output_dir = os.path.join(model_path, frb_name)
            u.mkdir_check(model.output_dir)
        model.name = frb_name
        mag_tbl, flux_tbl = get_mags_shifted(
            model=model,
            z_max=6.,
            n=2000,
            bands=bands_default + bands_wise,
            write=write
        )
        model_dict_frb["mag_table"] = mag_tbl

        mag_tbl.write(
            mag_table_path(frb_name=frb_name),
            overwrite=True
        )
        flux_tbl.write(
            flux_table_path(frb_name=frb_name),
            overwrite=True
        )

        # model_dict_frb["model"].write(os.path.join(model_path, f"{frb_name}_model_table.ecsv"))

        del model_dict_frb["mag_table"]
        del model_dict_frb["model"]


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(
        description=description
    )

    parser.add_argument(
        "-o",
        help="Path to output directory.",
        type=str,
        default=default_output_path
    )
    parser.add_argument(
        "-i",
        help="Path to directory containing input files.",
        type=str,
        default=default_input_path
    )
    parser.add_argument(
        "-c",
        help="Preferred cosmology. Should be listed in astropy.cosmology.available.",
        type=str,
        default="Planck18"
    )
    parser.add_argument(
        "--write",
        help="Write all redshifted models to disk? Will take up a LOT of space.",
        action="store_true"
    )

    args = parser.parse_args()
    output_path = args.o
    input_path = args.i
    main(
        output_dir=output_path,
        input_dir=input_path,
        cosmo=args.c,
        write=args.write
    )
