data: 
  ACS-GC: |
    FITS files constituting the entire ACS-GC catalogue; will be downloaded by the script `00-retrieve.py` from https://cdsarc.cds.unistra.fr/ftp/J/ApJS/200/9/fits/.
  chrimes+2021: |
    The Chrimes et al 2021 neutron star catalogue; will be downloaded by the script `00-retrieve.py` from https://raw.githubusercontent.com/achrimes2/MW-NS-Flight/refs/heads/master/Data/
data_availability: To inquire after the data used by these scripts, please contact me directly.
dir_description: |
  The scripts found in this directory are for reproducing the results in Chapter 3 of my forthcoming PhD thesis.
prerequisites:
  astropy: 5.0.4
  craft-optical-followup:
    release: v0.5-phd-thesis
    url: 'https://github.com/Lachimax/craft-optical-followup'
  matplotlib: 3.5.2
  numpy: 1.22.3
references: [
  'Bhardwaj, M. et al 2024:
    *Selection bias obfuscates the discovery of fast radio burst sources*
    Nature 634:8036
    [https://doi.org/10.1038/s41586-024-08065-w]',
  "Griffith, R. et al 2012: 
    *The Advanced Camera for Surveys General Catalog: Structural Parameters for Approximately Half a Million Galaxies*, 
    ApJS 200:1
    [https://doi.org/10.1088/0067-0049/200/1/9]"
]